---
title: "My dashboard"
author: "Luan Mugarte"
date: "`r Sys.Date()`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme: 
      version: 4
      bootswatch: minty
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F}
pacman::p_load(
  rio,             # data import/export     
  here,            # locate files
  tidyverse,       # data management and visualization
  flexdashboard,   # dashboard versions of R Markdown reports
  shiny,           # interactive figures
  plotly,          # interactive figures
  DT               # interactive tables
)
```

```{r, include = F}
source('extracao_limpeza_dados.R', echo = F)
source('elaboracao_graficos.R', echo = F)
```

# Inflação no Brasil {data-icon="fa-signal"}

### Inflação no Brasil nos anos 2000 {data-width=700}
```{r, echo = F}
p_ipca_cheio
```

### Comentário {data-width=700}

LALALALALALALLLLLLLLLLLLLLLLLLLLLLLALALALALAL

## E no período da pandemia? {data-width=700}


### Inflação por categorias {data-width=700}
```{r, echo = F}
p_ipca_categorias_acum

p_ipca_categorias_doze
```

## E a inflação onde eu moro?

### Inflação por município ou região metropolitana
```{r, echo = F}
tabela_categorias
```

## Tabela por município ou região metropolitana
```{r, echo = F}
tabela_rm_municipio
```

