#### Carregando pacotes ####

library(AER)
library('readxl') # Carrega dados do excel
# library('normtest') # Para testar normalidade dos res??duos
library(xts) # Objeto xts
# library('dynlm') # Para dinamicos
# library(sandwich)
# library(strucchange)
library(urca)
# library(FinTS)
library(gmm)
library(purrr)
# library(seasonal)
# library(x13binary)
library(smooth)
# library(forecast)
library(tidyverse)
library(zoo)
library(vars)
library(tseries)
# library(PerformanceAnalytics)
# library(quantmod)
# library(TTR)
# library(rugarch)
# library(mFilter)
library(cowplot)
library(scales)
library(RColorBrewer)
# library(PNADcIBGE)
# library(convey)
# library(survey)
library(tidyr)
# library(ineq)
# library(IC2)
library(dplyr)
library(tibble)
library(ggplot2)
library(car)
library(AER)
library(knitr)
library(stargazer)
library(broom)
# library(lmtest)
library(stats)
# library(olsrr)
# library(sandwich)
# library(doMC)
# library(lpirfs)
library(RcppRoll)
library(plotly)
# library(plyr)

#### Outras Configurações ###
# options(digits=4)
# # source("covEWMA.R")
# registerDoMC(2)
# library(devtools)
# install_github("MatthieuStigler/tsDyn", ref="Dev94", subdir="tsDyn")
# source('~/Dissertacao/ScriptsR/rootsTVAR.R', echo=TRUE)
